### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by joshbrown50** [architdate/animedl#1]
Could you give an example of the syntax that is supposed to be used? I understand mode (selecting either cr or funi) and url is obvious, but I can't tell what < res > is supposed to be. What is it? What is the syntax supposed to look like? I've searched everywhere I can think of and I can't find a reference to what it's supposed to be. It's just listed as a required argument.

**Comment by joshbrown50** [comment]
I've figured out now that its resolution. If I use 1080p it will bring up options for bandwidth qualities, but when I select any of them, it says streamlink not found

**Comment by architdate** [comment]
install packages from requirements.txt using `pip install -r requirements.txt`

**Comment by architdate** [comment]
Closing the issue for now, reopen if you are unable to resolve this

**Comment by joshbrown50** [comment]
I installed all requirements, but when I go to download something, it says /bin/sh: 1: streamlink: not found


python3 animedl.py --funi https://www.funimation.com/shows/uzaki-chan-wants-to-hang-out/uzaki-chan-wants-to-hang-out 1080p
[INFO] Uzaki-chan Wants to Hang Out! - S1E1 - Uzaki-chan Wants to Hang Out!
01 [1119221] Japanese - Simulcast
[INFO] Available qualities:
01 Resolution: 1080p [Bandwidth: 10132KiB/s]
02 Resolution: 1080p [Bandwidth: 10132KiB/s]
03 Resolution: 1080p [Bandwidth: 10132KiB/s]
04 Resolution: 1080p [Bandwidth: 8212KiB/s]
05 Resolution: 1080p [Bandwidth: 8212KiB/s]
06 Resolution: 1080p [Bandwidth: 8212KiB/s]
Select the stream to download: 1
streamlink --hls-segment-threads 5 --force "https://22-cf-10fad4b4a7894c10a47117386cbbce08.vip1-lga1.dlvr1.net/30216c86-c622-11ea-8caf-0ae255e47b3e/FunimationStoreFront/2237034/Japanese/2237034_Japanese_42a70238-09bc-ea11-82a8-dd291e252010_Layer10.m3u8" live -o "/home/josh/anime/animedl/Uzaki-chan Wants to Hang Out - S1E1 - Uzaki-chan Wants to Hang Out.ts"
/bin/sh: 1: streamlink: not found
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
/home/josh/anime/animedl/Uzaki-chan Wants to Hang Out - S1E1 - Uzaki-chan Wants to Hang Out.ts: No such file or directory

**Comment by joshbrown50** [comment]
So I took the time to set up and install everything on my windows system and it seems to work fine there. Its just my linux install that has this problem.

**Comment by joshbrown50** [comment]
I did get it working on windows at least. Thank you so much for making this. Trying to use youtube-dl was so tedious because it wouldn't download subtitles. I'd have to go in manually in my browser in developer mode and find the subtitle file and download it separately. 
I really appreciate being able to run 1 batch file and have everything download into its proper place. Thank you

**Comment by architdate** [comment]
Appreciated :)
